# Generated by Django 5.0.6 on 2024-06-07 21:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='title',
        ),
        migrations.AddField(
            model_name='ticket',
            name='asunto',
            field=models.TextField(default='Escribe aquí tu asunto', max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='departamento',
            field=models.TextField(default='Sin departamento', max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='estado',
            field=models.CharField(default='Sin departamento', max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='proyecto',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='titulo',
            field=models.CharField(default='Sin título', max_length=200),
        ),
    ]
