# Generated by Django 5.0.6 on 2024-06-08 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_description_remove_ticket_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='asunto',
            field=models.TextField(max_length=100, verbose_name='asunto'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departamento',
            field=models.TextField(max_length=200, verbose_name='departamento'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(max_length=200, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='proyecto',
            field=models.TextField(max_length=200, verbose_name='proyecto'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='titulo'),
        ),
    ]
